variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_file" {}
variable "primary_region" {}
variable "standby_region" {}
variable "compartment_id" {}
variable "namespace" {}
variable "bucket_primary" {}
variable "bucket_standby" {}